//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Lax.Mvc.AdminLte.Bootstrap {

    /// <summary>
    ///    Eine stark typisierte Ressourcenklasse zum Suchen nach lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder-Klasse
    // mithilfe eines Tools wie ResGen oder Visual Studio automatisch generiert.
    // Bearbeiten Sie zum Hinzufügen oder Entfernen eines Members die RESX-Datei, und führen Sie dann ResGen
    // mit der Option "/str" erneut aus, oder erstellen Sie das VS-Projekt erneut.
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Ressources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        internal Ressources() {
        }
        
        /// <summary>
        ///    Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("BootstrapTagHelpers.Ressources", typeof(Ressources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Überschreibt die Eigenschaft 'CurrentUICulture' des aktuellen Threads für alle
        ///    Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Sucht nach einer lokalisierten Zeichenfolge, die 'Close' ähnelt.
        /// </summary>
        internal static string CloseIconText {
            get {
                return ResourceManager.GetString("CloseIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Sucht nach einer lokalisierten Zeichenfolge, die 'current' ähnelt.
        /// </summary>
        internal static string CurrentPaginationItem {
            get {
                return ResourceManager.GetString("CurrentPaginationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Sucht nach einer lokalisierten Zeichenfolge, die 'Next' ähnelt.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Sucht nach einer lokalisierten Zeichenfolge, die 'Complete' ähnelt.
        /// </summary>
        internal static string PorgressBarCompleteSrHint {
            get {
                return ResourceManager.GetString("PorgressBarCompleteSrHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Sucht nach einer lokalisierten Zeichenfolge, die 'Previous' ähnelt.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Sucht nach einer lokalisierten Zeichenfolge, die 'Toggle navigation' ähnelt.
        /// </summary>
        internal static string ToggleNavigation {
            get {
                return ResourceManager.GetString("ToggleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Sucht nach einer lokalisierten Zeichenfolge, die 'error' ähnelt.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Sucht nach einer lokalisierten Zeichenfolge, die 'success' ähnelt.
        /// </summary>
        internal static string ValidationSuccess {
            get {
                return ResourceManager.GetString("ValidationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Sucht nach einer lokalisierten Zeichenfolge, die 'warning' ähnelt.
        /// </summary>
        internal static string ValidationWarning {
            get {
                return ResourceManager.GetString("ValidationWarning", resourceCulture);
            }
        }
    }
}
